// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "github.com/Nikkoz/task-service/pkg/context"
	mock "github.com/stretchr/testify/mock"

	service "github.com/Nikkoz/task-service/internal/service"

	user "github.com/Nikkoz/task-service/internal/domain/user"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, in
func (_m *Service) Login(ctx context.Context, in service.LoginInput) (service.LoginResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 service.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.LoginInput) (service.LoginResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.LoginInput) service.LoginResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(service.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.LoginInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in
func (_m *Service) Register(ctx context.Context, in service.RegisterInput) (user.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) (user.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) user.User); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
